# workflow to test the api
name: test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        mongodb-version: ['5.0']
        mongodb-port: [42069]
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: ${{ matrix.mongodb-port }}

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3

      - name: create test env file
        run: |
          cd tests
          touch .env
          echo DB_NAME=test >> .env
          echo MONGODB_URI=mongodb://localhost:${{ matrix.mongodb-port }}/test >> .env
          echo PORT=8080 >> .env
          echo CLIENT_URL=http://localhost:3000 >> .env
          echo BCRYPT_COST=10 >> .env
          echo RSA_KEY_SIZE=2048 >> .env
          cd ..

      - run: go test ./tests -tags test