# workflow to test the api
name: test
on: [push]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
      - name: Start containers
        run: docker-compose -f "/tests/docker-compose.yml" up -d --build

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - uses: actions/checkout@v3

      - name: create test env file
        run: |
          cd tests
          touch .env
          echo DB_NAME=test >> .env
          echo MONGODB_URI=mongodb://localhost:${{ matrix.mongodb-port }}/test >> .env
          echo PORT=8080 >> .env
          echo CLIENT_URL=http://localhost:3000 >> .env
          echo BCRYPT_COST=10 >> .env
          echo RSA_KEY_SIZE=2048 >> .env
          echo RELAY_HOST=localhost >> .env
          echo RELAY_PORT=5025 >> .env
          echo NOTIFICATION_INTERVAL=10 >> .env
          cd ..

      - run: go test ./tests -tags test

      - name: Stop containers
        run: docker-compose -f "/tests/docker-compose.yml" down